function createfigureIIR(X1, YMatrix1, X2, YMatrix2)
%CREATEFIGURE(X1, YMatrix1, X2, YMatrix2)
%  X1:  vector of plot x data
%  YMATRIX1:  matrix of plot y data
%  X2:  vector of plot x data
%  YMATRIX2:  matrix of plot y data

%  Auto-generated by MATLAB on 01-Nov-2023 17:54:51

% Create figure
figure1 = figure('Name','IIR Filter');

% Create subplot
subplot1 = subplot(2,1,1,'Parent',figure1);
hold(subplot1,'on');

% Create multiple line objects using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',subplot1);
set(plot1(1),'DisplayName','Eingangssignal');
set(plot1(2),'DisplayName','Ausgangssignal');

% Create ylabel
ylabel('u');

% Create xlabel
xlabel('t[s]');

% Create title
title('Signal');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[0 2]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[0 2750]);
box(subplot1,'on');
grid(subplot1,'on');
hold(subplot1,'off');
% Create legend
legend1 = legend(subplot1,'show');
set(legend1,...
    'Position',[0.741647244460747 0.60220507425136 0.153846151032648 0.0727848082403594]);

% Create subplot
subplot2 = subplot(2,1,2,'Parent',figure1);
hold(subplot2,'on');

% Create multiple line objects using matrix input to plot
plot2 = plot(X2,YMatrix2,'Parent',subplot2);
set(plot2(1),'DisplayName','Eingangsspektrum');
set(plot2(2),'DisplayName','Ausgangsspektrum');

% Create ylabel
ylabel('|FFT(u)|');

% Create xlabel
xlabel('f[Hz]');

% Create title
title('Spektrum');

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[0 1000000]);
box(subplot2,'on');
grid(subplot2,'on');
hold(subplot2,'off');
% Create legend
legend(subplot2,'show');

